@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Mar 05 14:37:52 -0500 2024
REM SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
REM
REM IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim TB_Phase_2_behav -key {Behavioral:sim_1:Functional:TB_Phase_2} -tclbatch TB_Phase_2.tcl -view C:/Users/james/ETS/Hiver_2024/ELE739/ELE739-Projet_2/Projet_2/TB_Phase_2_WaveDrom.wcfg -log simulate.log"
call xsim  TB_Phase_2_behav -key {Behavioral:sim_1:Functional:TB_Phase_2} -tclbatch TB_Phase_2.tcl -view C:/Users/james/ETS/Hiver_2024/ELE739/ELE739-Projet_2/Projet_2/TB_Phase_2_WaveDrom.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
